### ISSUE TITLE
AddMembers replaces entire group membership

### ISSUE THREAD

**Issue by rdev5** [GalacticAPI/Galactic#2]
This line effectively drops the entire membership of the target group and replaces it with the List<SecurityPrincipal> being passed in.

https://github.com/GalacticAPI/Galactic/blob/37cee66fe96ec4385e896c1d984534472de3b978/Galactic.ActiveDirectory/Group.cs#L208

Group X contains:
- User A
- User B
- User C

`g.AddMembers({ "User D" })`

Group X now contains:
- User D

**Comment by TrevorVass** [comment]
Yep you’re absolutely right. I’ll fix this and update GitHub and NuGet with new code / packages as soon as I can. Thanks for catching this!

Trevor

trevor@trevorvass.com

**Comment by TrevorVass** [comment]
Hi Matt, I've actually already fixed this. :) It was fixed in ea947870416a145b1f81c385f981d368c1306e6. It's available in version 1.0.0.33 of the library or newer. You can grab the newest version of it on Nuget here: https://www.nuget.org/packages/Galactic.ActiveDirectory/ . Thanks for using the library and finding bugs!
