### ISSUE TITLE
Password change

### ISSUE THREAD

**Issue by p10tyr** [GalacticAPI/Galactic#3]
Hi,
I have been trying to use your library, with muchmore success than the built in .NET ones.

I managed to connected to the LDAP and get the user I want, i can change attributes fine and they reflect on the LDAP. I use LDAPAdmin to check the changes.

How do I change the password for the user using the LDAP library? Setting userPassword doesnt work (i mean the text is there on the attribute but the AD wont login) When I use LDAPAdmin, there is a "set password" in the context menu on the "cn=my user", that does just the trick, I can log into the AD with the new password.

What I have is 

`List<string> server = new List<string>() { "lemy.ad.com" };`

 `Galactic.LDAP.LDAP ld = new Galactic.LDAP.LDAP(
                    server, 389, System.DirectoryServices.Protocols.AuthType.Negotiate,
                    "administrator", securePass, "DC=bla,DC=local"
                    );`

`var result = ld.Search("cn=my name");`

that works, and I can set attributes using 

`ld.AddOrReplaceAttribute(result.First().DistinguishedName, "userPassword", o);`

But how do I set a password, the correct way?

**Comment by p10tyr** [comment]
OK I realised I need to update the unicodePwd but I get False and not sure why. With the LDAP app it works so permissions are ok.

```
string password = "TestPassw0rd333";
string quotedPassword = "\"" + password + "\"";
byte[] unicode = System.Text.Encoding.Unicode.GetBytes(quotedPassword);

object[] o = new object[] { unicode };

bool success = ld.AddOrReplaceAttribute(result.First().DistinguishedName, "unicodePwd", o);
```

**Comment by p10tyr** [comment]
Ahh i just ditched this and used the DirectoryEntry in .NET and works straight away.

**Comment by TrevorVass** [comment]
Hi Peter, sorry I couldn't get back to you earlier. If you're connecting to Active Directory (it looks like you are), I would use the Galactic.ActiveDirectory library instead of the LDAP library. Galactic.ActiveDirectory uses the LDAP library under the hood but has already done a lot of the heavy lifting for you.
Pertaining to your problem above... in the Galactic.ActiveDirectory library you'd just create a user object based upon their Common Name and then set the password like so:

```
ActiveDirectory ad = new ActiveDirectory("blah.local", "DC=bla,DC=local",  "administrator", securePass);
User user = new User(ad.GetGUIDByCommonName("my name"));
user.SetPassword("theNewPassword");
```

I also have a quick tutorial going over the basics of the Active Directory library here:

https://github.com/GalacticAPI/GalacticExamples/tree/master/ActiveDirectoryExample

I hope this helps and let me know if you run into any other issues.
