### ISSUE TITLE
Should add explicit "Mono not supported" where applicable

### ISSUE THREAD

**Issue by jsumners** [GalacticAPI/Galactic#4]
Specifically, the LDAP and Active Directory libraries. I spent a good couple hours trying to figure out why I couldn't get it them to work. In the end, I backtracked how the Galactic APIs work while looking at the Mono source. Turns out the problem is Mono doesn't implement `LdapConnection` -- https://github.com/mono/mono/blob/HEAD/mcs/class/System.DirectoryServices.Protocols/System.DirectoryServices.Protocols/LdapConnection.cs

**Comment by TrevorVass** [comment]
I'm sorry you wasted a few hours on this. I will add a disclaimer. Towards that end, how did you get the library... via Nuget, searching GitHub or from the galactic.github.io page? Also since you're using Mono were you thinking about using the library on a non-Windows platform? (Just interested in the use case.) Thanks for catching this and I'll add the notice soon.

**Comment by jsumners** [comment]
Not really your fault. Mono needs to get their act together.

I found it via NuGet. I wanted a simple API instead of the base .Net one. And I was using Mono so I would have to install Visual Studio in a VM. The end goal is for the application to run on a Windows server.

**Comment by TrevorVass** [comment]
Sorry this took a while (work got hectic). I've updated the package descriptions in Nuget and committed new package templates into git. Thanks for bringing this up and using the library!
